### PR TITLE
Replacing ndictionary-parser for xml and xpath

### PR DESCRIPTION
**Pull request by nuxlli**
This PR replaces the ndictionary parser with one of xml, even adding two dependencies it makes the code simpler to be maintained between the versions of node.js

### CODE REVIEW

**Comment by daveallie** [comment]
Hi @nuxlli! I haven't bothered to look much over this repo since its inception.

Cloning your repo locally and attempting to use it results in the following exceptions:

```node
> macOSSpaces = require(".")
{ rawConfig: [Function: rawConfig],
  spaces: [Function: spaces],
  allSpaces: [Function: spacesByDisplay],
  spacesByDisplay: [Function: spacesByDisplay] }

> macOSSpaces.spaces(function(spaces) {
...   console.log(spaces);
... });
undefined
> TypeError: Cannot read property 'data' of null
    at /Users/david/repos/nuxlli/node-macos-spaces/index.js:30:43
    at Array.forEach (<anonymous>)
    at /Users/david/repos/nuxlli/node-macos-spaces/index.js:27:18
    at Array.forEach (<anonymous>)
    at /Users/david/repos/nuxlli/node-macos-spaces/index.js:21:16
    at /Users/david/repos/nuxlli/node-macos-spaces/index.js:9:5
    at ChildProcess.exithandler (child_process.js:267:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)

> macOSSpaces.allSpaces(function(spaces) {
...   console.log(spaces);
... });
undefined
> TypeError: Cannot read property 'data' of null
    at /Users/david/repos/nuxlli/node-macos-spaces/index.js:30:43
    at Array.forEach (<anonymous>)
    at /Users/david/repos/nuxlli/node-macos-spaces/index.js:27:18
    at Array.forEach (<anonymous>)
    at /Users/david/repos/nuxlli/node-macos-spaces/index.js:21:16
    at /Users/david/repos/nuxlli/node-macos-spaces/index.js:9:5
    at ChildProcess.exithandler (child_process.js:267:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
```

Happy to merge this in once it works

**Comment by nuxlli** [comment]
Okay, there must be differences in the xml structure (maybe between versions of macos).

Could you share with me the xml resulting from: `defaults export com.apple.spaces -`?

**Comment by daveallie** [comment]
https://gist.github.com/daveallie/8fa9a11209d33ddf030d0320039fc73a

The machine I tested it on is a hackintosh. 
image

For the record, the code on master atm works fine.

**Comment by nuxlli** [comment]
In fact the subtle differences between versions, in my case I'm with 10.13.3. It must have been this difference that caused the initial parser problem.

I've just figured out a better way to handle this, using the lib [plist](https://github.com/TooTallNate/plist.js) :)

Finally I added tests using my dump of yours.

**Comment by daveallie** [comment]
Awesome, thanks!

**Comment by daveallie** [comment]
Deployed v2.1.0 which includes these changes.

**Pull request merged**
